name: sharelatex-nightly

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  sharelatex-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone and reset to specific commit
        run: |
          git clone https://github.com/overleaf/overleaf.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push sharelatex-base
        uses: docker/build-push-action@v3
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile-base
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sharelatex-base:nightly
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/sharelatex-base:nightly

  sharelatex:
    needs: sharelatex-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        run: echo REVERSION=`git -C overleaf rev-parse HEAD` >> $GITHUB_ENV

      - name: Clone the latest commit
        run: |
          git clone --depth=1 https://github.com/overleaf/overleaf.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push sharelatex
        uses: docker/build-push-action@v3
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            SHARELATEX_BASE_TAG=${{ secrets.DOCKER_USERNAME }}/sharelatex-base
            MONOREPO_REVISION=${{ env.REVISION }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sharelatex:nightly
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/sharelatex:nightly