name: sharelatex-latest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run when the versioning json file change
  push:
    branches: [main]
    paths:
      - 'sharelatex.json'

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: prepare
        uses: ActionsTools/read-json-action@main
        with:
          file_path: 'sharelatex.json'
    outputs:
      versions: ${{steps.prepare.outputs.versions}}

  sharelatex-base:
    needs: prepare-environment
    runs-on: ubuntu-latest
    # Create a job for each version
    strategy:
      matrix:
        versions: ${{fromJson(needs.prepare-environment.outputs.versions)}}
    steps:
      - uses: actions/checkout@v3

      - name: Clone and reset to specific commit
        run: |
          git clone https://github.com/overleaf/overleaf.git
          git -C overleaf reset --hard ${{matrix.versions.sha}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push sharelatex-base
        uses: docker/build-push-action@v3
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile-base
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sharelatex-base:${{matrix.versions.tag}}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/sharelatex-base:${{matrix.versions.tag}}

  sharelatex:
    needs: [prepare-environment, sharelatex-base]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone and reset to specific commit
        run: |
          git clone https://github.com/overleaf/overleaf.git
          git -C overleaf reset --hard ${{matrix.versions.sha}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push sharelatex
        if: steps.filter.outputs.sharelatex == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            SHARELATEX_BASE_TAG=${{ secrets.DOCKER_USERNAME }}/sharelatex-base
            MONOREPO_REVISION=${{ steps.prepare-env.outputs.sha }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sharelatex:${{matrix.versions.tag}}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/sharelatex:${{matrix.versions.tag}}