name: Overleaf Image Auto Builder

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Auto run every day at 4 AM
  schedule:
    - cron: '0 0 * * 6'

jobs:
  sharelatex_base:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git clone --depth=1 https://github.com/overleaf/overleaf.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_PRI_REGISTRY}}
          username: ${{ secrets.DOCKER_PRI_USERNAME }}
          password: ${{ secrets.DOCKER_PRI_PASSWORD }}

      - name: Generate ARGS
        run: |
          echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile-base
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_PRI_REGISTRY}}/sharelatex-base:latest