name: sharelatex-base

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Auto run every Saturday
  schedule:
    - cron: '0 0 * * 6'

jobs:
  sharelatex-base:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git clone --depth=1 https://github.com/overleaf/overleaf.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate GitHub ENV
        run: |
          echo COMMIT_SHA=`git describe --tags --always` >> $GITHUB_ENV
          echo "SHARELATEX_BASE_TAG=${{ secrets.DOCKER_USERNAME }}/sharelatex-base" >> $GITHUB_ENV

      - name: Build and push sharelatex-base
        uses: docker/build-push-action@v3
        with:
          context: ./overleaf
          file: ./overleaf/server-ce/Dockerfile-base
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sharelatex-base:latest
            ${{ secrets.DOCKER_USERNAME }}/sharelatex-base:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=${{ env.SHARELATEX_BASE_TAG }}:latest